services:
  frontend_server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - server_net
    ports:
      - "3000:3000"
  backend_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - db_net
      - server_net
      - ollama_net
    ports:
      - "3001:3001"
    environment:
      - PYTHONPATH=${PYTHONPATH}:/src/
    env_file:
      - .env.back
  db:
    image: mongo:4.4
    restart: always
    networks:
      - db_net
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - .env.db
    volumes:
      - db_megical:/data/db

  ollama:
    image: ollama/ollama
    networks:
      - ollama_net
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


networks:
  db_net:
    driver: bridge
  server_net:
    driver: bridge
  ollama_net:
    driver: bridge

volumes:
  db_megical:
  ollama_data: