services:
  frontend_server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/src/
    networks:
      - server_net
    ports:
      - "3000:3000"
  backend_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - db_net
      - server_net
      - ollama_net
    volumes:
      - ./backend/:/src/
    ports:
      - "3001:3001"
    environment:
      - PYTHONPATH=${PYTHONPATH}:/src/
    env_file:
      - .env.back
  db:
    image: mongo:4.4
    restart: always
    networks:
      - db_net
    volumes:
      - db_megical:/src/
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - .env.db

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    networks:
      - ollama_net


networks:
  db_net:
    driver: bridge
  server_net:
    driver: bridge
  ollama_net:
    driver: bridge

volumes:
  db_megical: